sudo: false
dist: trusty
language: perl
perl:
    # ~stretch
    - "5.24-shrplib"
    # ~xenial
    # - "5.22-shrplib"
    # ~jessie
    # - "5.20-shrplib"
    # ~trusty
    # - "5.18-shrplib"
    - "system-perl"
env:
    - CC=clang UNITTESTS=false
    - CC=gcc   UNITTESTS=false
    - CC=clang UNITTESTS=true
matrix:
    exclude:
        - env: CC=clang UNITTESTS=true
          perl: "system-perl"
    allow_failures:
        - env: CC=clang UNITTESTS=true

addons:
    apt:
        packages:
            - libperl-dev
            - elinks

before_install:
    - perl -V
    - ./autogen.sh --with-proxy --with-bot --with-perl=module
    - make dist
    - cd ..
    - tar xaf */irssi-*.tar.*
    - cd irssi-*

install:
    - ./configure --with-proxy --with-bot --with-perl=module --with-otr=no --prefix=$HOME/irssi-build
      $( $UNITTESTS && echo --enable-always-build-tests )
    - make CFLAGS="-Wall -Werror -Werror=declaration-after-statement"
    - make install

before_script:
    - pushd ~
    - mkdir irssi-test
    - echo echo automated irssi launch test > irssi-test/startup;
      echo ^set settings_autosave off >> irssi-test/startup;
      echo ^set -clear log_close_string >> irssi-test/startup;
      echo ^set -clear log_day_changed >> irssi-test/startup;
      echo ^set -clear log_open_string >> irssi-test/startup;
      echo ^set log_timestamp '* ' >> irssi-test/startup;
      echo ^window log on >> irssi-test/startup
    - echo load perl >> irssi-test/startup
    - echo load proxy >> irssi-test/startup
    - echo ^quit >> irssi-test/startup

script:
    - irssi-build/bin/irssi --home irssi-test
    - popd
    - if $UNITTESTS; then make -C tests -sk check; fi

after_script:
    - cat ~/irc.log.*
    - find -name test-suite.log -exec cat {} +
