/*
 * Off-the-Record Messaging (OTR) modules for IRC
 *
 * Copyright (C) - 2012  David Goulet <dgoulet@ev0ke.net>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301,USA
 */

#ifndef IRSSI_OTR_FORMATS_H
#define IRSSI_OTR_FORMATS_H

#include "formats.h"

/*
 * Must be in sync with the fe_otr_formats array.
 */
enum otr_status_format {
	TXT_OTR_MODULE_NAME,

	/* Status bar format. */
	TXT_OTR_FILL_1,
	TXT_OTR_STB_PLAINTEXT,
	TXT_OTR_STB_FINISHED,
	TXT_OTR_STB_UNKNOWN,
	TXT_OTR_STB_UNTRUSTED,
	TXT_OTR_STB_TRUST,

	/* OTR format. */
	TXT_OTR_FILL_2,
	TXT_OTR_KEY_GENERATION_ERROR,
	TXT_OTR_KEY_GENERATION_COMPLETED,
	TXT_OTR_KEY_GENERATION_STARTED,
	TXT_OTR_KEY_GENERATION_RUNNING,
	TXT_OTR_FINGERPRINT_INFO,
	TXT_OTR_ERROR_NO_KEYS,
	TXT_OTR_SESSION_ALREADY_SECURED,
	TXT_OTR_SESSION_INITIATING,
	TXT_OTR_SESSION_FINISHED,
	TXT_OTR_CONTEXT_MISSING_ERROR,
	TXT_OTR_CONTEXT_MISSING_NICK_ERROR,
	TXT_OTR_CONTEXT_LIST_HEADER,
	TXT_OTR_CONTEXT_LIST_ENCRYPTED_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_PLAINTEXT_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_FINISHED_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_UNKNOWN_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_UNUSED_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_SMP_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_MANUAL_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_UNVERIFIED_STATE_LINE,
	TXT_OTR_CONTEXT_LIST_FOOTER,
	TXT_OTR_FINALIZE_NOTHING_TO_DO,
	TXT_OTR_FINALIZE_COMPLETED,
	TXT_OTR_AUTH_MISSING_SESSION_ERROR,
	TXT_OTR_FINGERPRINT_NOT_FOUND,
	TXT_OTR_ALREADY_TRUSTED_ERROR,
	TXT_OTR_FINGERPRINT_TRUSTED,
	TXT_OTR_ALREADY_DISTRUSTED_ERROR,
	TXT_OTR_FINGERPRINT_DISTRUSTED,
	TXT_OTR_FINGERPRINT_FORGOTTEN,
	TXT_OTR_FINGERPRINT_CONTEXT_ENCRYPTED,
	TXT_OTR_AUTHENTICATION_ABORTED,
	TXT_OTR_AUTHENTICATION_ONGOING_ABORTED,
	TXT_OTR_AUTHENTICATION_INITIATED,
	TXT_OTR_AUTHENTICATION_RESPONSE,
	TXT_OTR_MESSAGE_EVENT_ENCRYPTION_REQUIRED,
	TXT_OTR_MESSAGE_EVENT_ENCRYPTION_ERROR,
	TXT_OTR_MESSAGE_EVENT_CONNECTION_ENDED,
	TXT_OTR_MESSAGE_EVENT_MALFORMED_MESSAGE,
	TXT_OTR_MESSAGE_EVENT_ERROR,
	TXT_OTR_MESSAGE_EVENT_MESSAGE_REFLECTED,
	TXT_OTR_MESSAGE_EVENT_MESSAGE_RESENT,
	TXT_OTR_MESSAGE_EVENT_RECEIVED_MESSAGE_NOT_IN_PRIVATE,
	TXT_OTR_MESSAGE_EVENT_RECEIVED_MESSAGE_UNREADABLE,
	TXT_OTR_MESSAGE_EVENT_RECEIVED_MESSAGE_MALFORMED,
	TXT_OTR_MESSAGE_EVENT_RECEIVED_MESSAGE_ERROR,
	TXT_OTR_MESSAGE_EVENT_RECEIVED_MESSAGE_UNENCRYPTED,
	TXT_OTR_MESSAGE_EVENT_RECEIVED_MESSAGE_UNRECOGNIZED,
	TXT_OTR_SMP_SECRET_QUESTION,
	TXT_OTR_SMP_ANSWER_HEADER,
	TXT_OTR_SMP_ANSWER_QUESTION,
	TXT_OTR_SMP_ANSWER_FOOTER,
	TXT_OTR_SMP_IN_PROGRESS,
	TXT_OTR_SMP_SUCCESS,
	TXT_OTR_SMP_FAILURE,
	TXT_OTR_SECURE,
	TXT_OTR_INSECURE,
	TXT_OTR_UNAUTHENCIATED_PEER_WARNING,
	TXT_OTR_LOCAL_FINGERPRINT,
	TXT_OTR_REMOTE_FINGERPRINT
};

extern FORMAT_REC fe_otr_formats[];

#endif /* IRSSI_OTR_FORMATS_H */
